"""add_performance_indexes

Revision ID: 2231f2f2a2a8
Revises: c1eafc1ff336
Create Date: 2025-07-03 01:52:49.100998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2231f2f2a2a8'
down_revision = 'c1eafc1ff336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.create_index('idx_strategy_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index('idx_tag_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.create_index('idx_trade_account', ['account'], unique=False)
        batch_op.create_index('idx_trade_direction', ['direction'], unique=False)
        batch_op.create_index('idx_trade_entry_date', ['entry_date'], unique=False)
        batch_op.create_index('idx_trade_exit_date', ['exit_date'], unique=False)
        batch_op.create_index('idx_trade_pnl', ['pnl'], unique=False)
        batch_op.create_index('idx_trade_strategy_id', ['strategy_id'], unique=False)
        batch_op.create_index('idx_trade_ticker', ['ticker'], unique=False)
        batch_op.create_index('idx_trade_user_entry_date', ['user_id', 'entry_date'], unique=False)
        batch_op.create_index('idx_trade_user_exit_date', ['user_id', 'exit_date'], unique=False)
        batch_op.create_index('idx_trade_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_trade_user_pnl', ['user_id', 'pnl'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_index('idx_trade_user_pnl')
        batch_op.drop_index('idx_trade_user_id')
        batch_op.drop_index('idx_trade_user_exit_date')
        batch_op.drop_index('idx_trade_user_entry_date')
        batch_op.drop_index('idx_trade_ticker')
        batch_op.drop_index('idx_trade_strategy_id')
        batch_op.drop_index('idx_trade_pnl')
        batch_op.drop_index('idx_trade_exit_date')
        batch_op.drop_index('idx_trade_entry_date')
        batch_op.drop_index('idx_trade_direction')
        batch_op.drop_index('idx_trade_account')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index('idx_tag_user_id')

    with op.batch_alter_table('strategy', schema=None) as batch_op:
        batch_op.drop_index('idx_strategy_user_id')

    # ### end Alembic commands ###
