"""Add account field to Trade model

Revision ID: 735f4de5bb4f
Revises: abdfe95bde6b
Create Date: 2025-07-02 20:38:19.695614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735f4de5bb4f'
down_revision = 'abdfe95bde6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        # First add the column as nullable
        batch_op.add_column(sa.Column('account', sa.String(length=100), nullable=True))
    
    # Update existing rows with default value
    op.execute("UPDATE trade SET account = 'Default' WHERE account IS NULL")
    
    # Then make it NOT NULL
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.alter_column('account', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('account')

    # ### end Alembic commands ###
