"""Add composite index for calendar performance optimization

Revision ID: 7636c2f0f036
Revises: 2231f2f2a2a8
Create Date: 2025-07-03 11:23:51.555902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7636c2f0f036'
down_revision = '2231f2f2a2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.create_index('idx_trade_user_entry_pnl', ['user_id', 'entry_date', 'pnl'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_index('idx_trade_user_entry_pnl')

    # ### end Alembic commands ###
